const { publishEvent } = require("../producer/eventProducer");
const EVENTS = require("../events/eventTypes");
const { v4: uuidv4 } = require("uuid");


const createEvent = async (req, res) => {
  try {
    console.log("POST request received");
    console.log("Request body: ", req.body);

    // Input validation
    const { seats } = req.body;
    if (seats === undefined || seats === null || typeof seats !== 'number' || seats <= 0 || !Number.isInteger(seats)) {
      return res.status(400).json({
        error: "Invalid input",
        message: "seats must be a positive integer"
      });
    }

    // const { bookingId, eventId, userId, seats } = req.body;
    const bookingId = uuidv4();
    const eventId = uuidv4();
    const userId = uuidv4();
    // NOTE: In a real system, these IDs are generated by the core booking service (MongoDB)
    // This controller simulates upstream systems for event processing demonstration.

    const idempotencyKey = `reserve:${bookingId}`;

    await publishEvent({
      eventType: EVENTS.SEATS_RESERVED,
      idempotencyKey,
      payload: {
        bookingId,
        eventId,
        userId,
        seats,
      },
    });

    res.status(202).json({
      message: "Event received successfully",
      data: req.body
    });
  } catch (error) {
    console.error("Error in createEvent:", error);
    res.status(500).json({
      error: "Internal server error",
      message: "Failed to process event"
    });
  }
};

module.exports = {
  createEvent
};
